name: Time changer plugin
main: me.s4wa.time_changer_plugin
version: SNAPSHOT
commands:
 playertime:
  description: It will can change own time.
  usage: /<command>
  default: true
  aliases: pt