name: Time changer plugin
main: me.s4wa.time_changer_plugin
version: 1.0
commands:
 playertime:
  description: It will can change own time.
  usage: /<command> (day, noon, night, reset)
  default: true
  aliases: pt
